services:
  c1-frontend-api:
    build: ./c1-frontend-api
    ports:
      - "7071:7071"
    environment:
      RABBITMQ_HOST: c2-rabbitmq
      RABBITMQ_USER: appuser
      RABBITMQ_PASS: apppass
      C5_API_URL: http://c5-storage-api:3000
    depends_on:
      - c2-rabbitmq
      - c5-storage-api


  c2-rabbitmq:
    build: ./c2-rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: apppass
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  c3-consumer:
    build: ./c3-consumer
    environment:
      RABBITMQ_HOST: c2-rabbitmq
      RABBITMQ_USER: appuser
      RABBITMQ_PASS: apppass
      C5_API_URL: http://c5-storage-api:3000
    volumes:
      - ./c3-output:/data/output
      - ./mpi-work:/mpi-work
      - ./secrets/mpi:/ssh-secrets
    depends_on:
      - c2-rabbitmq
      - c5-storage-api
      - c4-worker-1
      - c4-worker-2
      - c4-worker-3

  c4-worker-1:
    build: ./c4-worker
    image: ismclean-c4-worker
    hostname: c4-worker-1
    volumes:
      - ./mpi-work:/mpi-work
      - ./secrets/mpi:/ssh-secrets

  c4-worker-2:
    image: ismclean-c4-worker
    pull_policy: never
    hostname: c4-worker-2
    depends_on:
      - c4-worker-1
    volumes:
      - ./mpi-work:/mpi-work
      - ./secrets/mpi:/ssh-secrets

  c4-worker-3:
    image: ismclean-c4-worker
    pull_policy: never
    hostname: c4-worker-3
    depends_on:
      - c4-worker-1
    volumes:
      - ./mpi-work:/mpi-work
      - ./secrets/mpi:/ssh-secrets

  c5-storage-api:
    build: ./c5-storage-api
    ports:
      - "3005:3000"
    environment:
      MYSQL_HOST: c5-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bmpdb
      MYSQL_USER: kevinuser
      MYSQL_PASSWORD: kevinpass
    depends_on:
      - c5-mysql

  c5-mysql:
    build: ./c5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bmpdb
      MYSQL_USER: kevinuser
      MYSQL_PASSWORD: kevinpass
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data:
